import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import {SoundEffect} from "@/components/SoundEffect/SoundEffect";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pressStart2P = Press_Start_2P({
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={pressStart2P.className}
      >
        <header>
        header
        </header>
        {children}
        <footer>
footer
        </footer>
      </body>
      <SoundEffect />
    </html>
  );
}
